setlocal autoindent
setlocal colorcolumn=80
setlocal fileformat=unix
setlocal formatoptions=croql
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal tabstop=4
setlocal textwidth=79
let python_highligh_all=1
